// <auto-generated />
using FolhaPagamentoService.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FolhaPagamentoService.Data.Migrations
{
    [DbContext(typeof(FolhaPagamentoContext))]
    [Migration("20211207034853_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FolhaPagamentoService.Business.Models.FolhaPagamento", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("DescontoInss")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("DescontoIrrf")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("DescontoPlanoSaude")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("FuncionarioId")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("SalarioBruto")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("SalarioLiquido")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("FolhasPagamento");
                });
#pragma warning restore 612, 618
        }
    }
}
